### ISSUE TITLE
Fails if OSA commits are the same

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc_differ#2]
The following fails on version 0.0.3 because the two RPCO tags use the same OSA SHA

rpc-differ r11.1.16 r11.1.17

**Comment by alextricity25** [comment]
I'll take a stab at fixing this.

**Comment by major** [comment]
Thanks, @alextricity25! :)

![Teamwork](https://media.tenor.co/images/7a9a1dbb5c0abcf1539b79d12099ca84/raw)
